version: 2.1

jobs:
  build-test:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - run:
          name: "build and test"
          command: |
            pip install -r requirements.txt
            pytest --html=report.html --self-contained-html --junitxml=report.xml
      - store_artifacts:
          path: ~/project/report.html
      - store_test_results:
          path: ~/project/report.xml

workflows:
  build-run-workflow:
    jobs:
      - build-test