version: 2.1

jobs:
  build-run:
    docker:
      - image: cimg/python:3.10.2

    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: "build and run"
          command: |
            pip install -r requirements.txt
            pytest
      - store_artifacts:
          path: /tmp
          destination: report.html

workflows:
  build-run-workflow:
    jobs:
      - build-run