version: 2.1

jobs:
  build-run:
    docker:
      - image: cimg/python:3.10.2

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "build and run"
          command: |
            pwd
            pip install -r requirements.txt
            pytest --html=report.html --self-contained-html
      - store_artifacts:
          path: ~/project/report.html

workflows:
  build-run-workflow:
    jobs:
      - build-run