version: 2.1

jobs:
  build-run:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: "build and run"
          command: |
            pip install -r requirements.txt
            pytest

workflows:
  build-run-workflow:
    jobs:
      - build-run