version: 2.1

jobs:
  build-env:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: "build"
          command: |
            pip install -r requirements.txt
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  tests-run:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "run"
          command: |
            pytest --html=report.html --self-contained-html --junitxml=report.xml
      - store_artifacts:
          path: ~/project/report.html
      - store_test_results:
          path: ~/project/report.xml

workflows:
  build-run-workflow:
    jobs:
      - build-env
      - tests-run:
          requires:
            - build-env